//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public string Doctor_Id { get; set; }
        public string Doctor_Name { get; set; }
        public string Phone { get; set; }
    
        public virtual DoctorDegree DoctorDegree { get; set; }
    }
}
