//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicinRank
    {
        public int Med_Id { get; set; }
        public Nullable<int> Ranking { get; set; }
        public string Doctor_Id { get; set; }
    
        public virtual Medicin Medicin { get; set; }
    }
}
