//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHandler
{
    using System;
    using System.Collections.Generic;
    public partial class Medicates
    {
        public int Pres_Id { get; set; }
        public string Med_Name { get; set; }
        public string timings { get; set; }
    }

        public partial class Medication
    {
        public int Pres_Id { get; set; }
        public int Med_Id { get; set; }
        public string timings { get; set; }
    
        public virtual Medicin Medicin { get; set; }
        public virtual Medicin Medicin1 { get; set; }
    }
}
