//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public int Pres_Id { get; set; }
        public int patient_Id { get; set; }
        public System.DateTime St_Date { get; set; }
        public Nullable<System.DateTime> E_Date { get; set; }
        public string Results { get; set; }
        public string Doctor_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
